version: "3"

networks:
  monitoring:
    driver: bridge

services:

  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      # - "15692:15692"
    # environment:
    #   - RABBITMQ_DEFAULT_USER=guest
    #   - RABBITMQ_DEFAULT_PASS=guest
    #   - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - monitoring
    restart: always


  prometheus:
    image: bitnami/prometheus
    container_name: prometheus
    hostname: prometheus
    depends_on:
      - rabbitmq
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      # - '--storage.tsub.path=/prometheus'
      # - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      # - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring
    restart: always
    
  grafanaservices:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    depends_on:
      - prometheus
      - rabbitmq
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: always
    volumes:
      - ../bin/grafana/grafana_data:/var/lib/grafana
      - ../bin/grafana/provisioning/:/etc/grafana/provisioning/
